cleanup: remove unused methods and struct
Error: internal/timelog/timelog.go:10:2: field `startTime` is unused
(unused)
  startTime time.Time
  ^
  Error: internal/timelog/timelog.go:18:6: func `isSlackingTime` is
unused (unused)
  func isSlackingTime(input string) bool {
       ^
  Error: internal/timelog/timelog.go:22:6: func `parseTextInput` is
unused (unused)
  func parseTextInput(input string) {
       ^
  Error: internal/timelog/timelog.go:26:6: func `appendFile` is unused
(unused)
  func appendFile(input string) {
       ^